FROM alpine:3.22 as builder

WORKDIR /Downloads

RUN apk update && wget https://github.com/bluenviron/mediamtx/releases/download/v1.17.1/mediamtx_v1.17.1_linux_amd64.tar.gz && tar -xvf mediamtx_v1.17.1_linux_amd64.tar.gz

FROM alpine:3.22

RUN apk update && apk add curl --no-cache

COPY --from=builder /Downloads/mediamtx /usr/bin/mediamtx

ENTRYPOINT ["/usr/bin/mediamtx"]
